//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDepuracionNNA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiviPola
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiviPola()
        {
            this.EncargoFiduciarioDep = new HashSet<EncargoFiduciarioDep>();
            this.EncargoFiduciarioDep1 = new HashSet<EncargoFiduciarioDep>();
        }
    
        public long codigo_departamento_municipio { get; set; }
        public Nullable<short> codigo_departamento { get; set; }
        public Nullable<short> codigo_municipio { get; set; }
        public string nombre_departamento { get; set; }
        public string nombre_municipio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncargoFiduciarioDep> EncargoFiduciarioDep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncargoFiduciarioDep> EncargoFiduciarioDep1 { get; set; }
    }
}
