//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDepuracionNNA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncargoFiduciario
    {
        public int Id1 { get; set; }
        public string id { get; set; }
        public string registro_uniqueidentifier { get; set; }
        public string anio { get; set; }
        public string rad { get; set; }
        public string proceso { get; set; }
        public string id_persona { get; set; }
        public string Primer_nombre_victima { get; set; }
        public string Segundo_nombre_victima { get; set; }
        public string primer_apellido_victima { get; set; }
        public string Segundo_apellido_victima { get; set; }
        public string genero_victima { get; set; }
        public string tipo_documento_victima { get; set; }
        public string no_documento_victima { get; set; }
        public string fecha_nacimiento_victima { get; set; }
        public string hecho_victimi { get; set; }
        public string hecho_victimi_depto_nombre { get; set; }
        public string hecho_victimi_muni_nombre { get; set; }
        public string hecho_victimi_fecha { get; set; }
        public string id_persona2 { get; set; }
        public string Primer_nombre_destinatario { get; set; }
        public string Segundo_nombre_destinatario { get; set; }
        public string primer_apellido_destinatario { get; set; }
        public string Segundo_apellido_destinatario { get; set; }
        public string genero_destinatario { get; set; }
        public string tipo_documento_destinatario { get; set; }
        public string NO_DOCUMENTO_DESTINATARIO { get; set; }
        public string fecha_nacimiento_destinatario { get; set; }
        public string parentesco_destinatario { get; set; }
        public string nombre_departamento { get; set; }
        public string nombre_municipio { get; set; }
        public string direccion { get; set; }
        public string Telefono_correspondencia { get; set; }
        public string fecha_declaracion { get; set; }
        public string porcentaje_recalculado { get; set; }
        public string LIQUIDACION_DEFINITIVA { get; set; }
        public string No_de_Resolución { get; set; }
        public string CONTARATO { get; set; }
        public string no_resolucion { get; set; }
        public string fecha_resolucion { get; set; }
        public string LIQUIDACION_DEFINITIVA1 { get; set; }
        public string No_de_Resolucion { get; set; }
    }
}
