//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDepuracionNNA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncargoFiduciarioDep
    {
        public int id { get; set; }
        public System.Guid registro_uniqueidentifier { get; set; }
        public string anio { get; set; }
        public string rad { get; set; }
        public string proceso { get; set; }
        public Nullable<long> id_persona_victima { get; set; }
        public string Primer_nombre_victima { get; set; }
        public string Segundo_nombre_victima { get; set; }
        public string primer_apellido_victima { get; set; }
        public string Segundo_apellido_victima { get; set; }
        public string genero_victima { get; set; }
        public string tipo_documento_victima { get; set; }
        public Nullable<long> no_documento_victima { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento_victima { get; set; }
        public string hecho_victimi { get; set; }
        public Nullable<System.DateTime> hecho_victimi_fecha { get; set; }
        public Nullable<long> id_persona_destinatario { get; set; }
        public string Primer_nombre_destinatario { get; set; }
        public string Segundo_nombre_destinatario { get; set; }
        public string primer_apellido_destinatario { get; set; }
        public string Segundo_apellido_destinatario { get; set; }
        public string genero_destinatario { get; set; }
        public string tipo_documento_destinatario { get; set; }
        public Nullable<long> NO_DOCUMENTO_DESTINATARIO { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento_destinatario { get; set; }
        public string parentesco_destinatario { get; set; }
        public string direccion { get; set; }
        public string Telefono_correspondencia { get; set; }
        public Nullable<System.DateTime> fecha_declaracion { get; set; }
        public Nullable<double> porcentaje_recalculado { get; set; }
        public Nullable<decimal> valor_total_pagar_indemnizacion { get; set; }
        public string CONTARATO { get; set; }
        public string no_resolucion { get; set; }
        public Nullable<System.DateTime> fecha_resolucion { get; set; }
        public string estadoPago { get; set; }
        public long hecho_victimi_muni_Codigo { get; set; }
        public long codigo_muni_Correspondencia_destinatario { get; set; }
    
        public virtual DiviPola HechoVictimiCodigo { get; set; }
        public virtual DiviPola MuniCorrespondenciaCodigo { get; set; }
    }
}
