//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDepuracionNNA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parentesco
    {
        public int id { get; set; }
        public string sigla { get; set; }
        public string nombre { get; set; }
        public Nullable<int> auditoria_usuario_creacion { get; set; }
        public Nullable<System.DateTime> auditoria_fecha_creacion { get; set; }
        public Nullable<int> auditoria_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> auditoria_fecha_modificacion { get; set; }
    }
}
