//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDepuracionNNA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public int idRol { get; set; }
        public int idEmpresa { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string tipo_documento { get; set; }
        public string no_documento { get; set; }
        public string correo_electronico { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> estado { get; set; }
        public string departamento_territorial { get; set; }
        public Nullable<System.DateTime> auditoria_fecha_creacion { get; set; }
        public Nullable<int> auditoria_usuario_creacion { get; set; }
        public Nullable<System.DateTime> auditoria_fecha_moficacion { get; set; }
        public Nullable<int> auditoria_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> auditoria_ultimo_ingreso_fecha { get; set; }
        public string auditoria_ultimo_ingreso_direccion_mac { get; set; }
        public string auditoria_ultimo_ingreso_direccion_ip { get; set; }
    }
}
