//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDepuracionNNA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_consultar_historico_nacional
    {
        public int id { get; set; }
        public string anio { get; set; }
        public string rad { get; set; }
        public Nullable<int> rad_hogar { get; set; }
        public string proceso { get; set; }
        public string subproceso { get; set; }
        public Nullable<int> tipo_registro_pago { get; set; }
        public string parentesco_destinatario { get; set; }
        public string estado_banco { get; set; }
        public Nullable<double> porcentaje_recalculado { get; set; }
        public string nombre_1_victima { get; set; }
        public string nombre_2_victima { get; set; }
        public string apellido_1_victima { get; set; }
        public string apellido_2_victima { get; set; }
        public string no_documento_victima { get; set; }
        public string nombre_1_destinatario { get; set; }
        public string nombre_2_destinatario { get; set; }
        public string apellido_1_destinatario { get; set; }
        public string apellido_2_destinatario { get; set; }
        public string no_documento_destinatario { get; set; }
    }
}
