//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDepuracionNNA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_consultaHistoricoNNAS
    {
        public int IdRegistro { get; set; }
        public string Radicado { get; set; }
        public string NombreVictima { get; set; }
        public string DocumentoVictima { get; set; }
        public string HechoVictimizante { get; set; }
        public string NombreDestinatario { get; set; }
        public string DocumentoDestinatario { get; set; }
        public string Proceso { get; set; }
    }
}
